### ISSUE TITLE
Better version update automation

### ISSUE THREAD

**Issue by rymsha** [enonic/release-tools#31]
Current code
```
      - name: Write new snapshot version
        if: steps.publish_vars.outputs.release == 'true'
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version'
          value: ${{ steps.publish_vars.outputs.nextSnapshot }}
```

Doe not notice version property if its defenition contains spaces
`version = 1.0.0-SNAPSHOT` - is not recognized

Write own automation that is more robust and migrate all repositories to it
